### ISSUE TITLE
canonical API methods list

### ISSUE THREAD

**Issue by cprice404** [momentohq/standards-and-practices#45]
We should add a page to the spec docs that shows the canonical list of APIs that each SDK should support.  We can copy this from the .NET or JS SDKs as a starting point and then tweak formatting as appropriate for a markdown reference.

Coordinate with Kirk about public docs.

**Comment by schwern** [comment]
https://www.notion.so/momentohq/SDK-API-Methods-Spec-cf12e4db2535405ca2acc3608814b083

**Comment by malandis** [comment]
:reminder_ribbon: private link on a public repo

**Comment by cprice404** [comment]
I am assuming we will PR the content to this repo soon.  But sure if you want to move the issue go ahead.
